# Generated by Django 2.2.2 on 2019-06-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_auto_20190628_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
