# Generated by Django 2.2.2 on 2019-08-01 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_productimage_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteapp.ProductImage'),
        ),
    ]
