# Generated by Django 2.2.2 on 2019-06-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_auto_20190627_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
    ]
