# Generated by Django 2.2.2 on 2019-06-05 17:19

from django.db import migrations, models
import siteapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=siteapp.models.images_folder),
        ),
    ]
