# Generated by Django 2.2.2 on 2019-08-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_remove_cartitem_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_image',
            field=models.ManyToManyField(to='siteapp.ProductImage'),
        ),
    ]
