# Generated by Django 2.2.2 on 2019-06-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_auto_20190627_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Image for POST', 'verbose_name_plural': 'Images for POSTS'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Image for PRODUCT', 'verbose_name_plural': 'Images for PRODUCTS'},
        ),
        migrations.AddField(
            model_name='product',
            name='price_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=10),
        ),
    ]
