# Generated by Django 2.2.2 on 2019-08-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0005_cartitem_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_image',
        ),
    ]
