# Generated by Django 2.2.2 on 2019-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0005_auto_20190628_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
