# Generated by Django 2.2.2 on 2019-08-05 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0007_cartitem_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_image',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
